### ISSUE TITLE
Rethink/rework "Feature Gaps" page

### ISSUE THREAD

**Issue by jcmeloni-usds** [usds/us-forms-system#108]
We have a page in the wiki around gaps: https://github.com/usds/us-forms-system/wiki/Inventory-of-Feature-Gaps

Some of these are things that belong in the list as actual feature gaps, and some are not.

In order for this page to be useful to outside viewers as well as something that helps guide our scope, please think about how to rework it to achieve the following:
* describe known features that do not currently exist in the library OR starter app, but are things we know we want to do (and why, and where they are in the prioritization). 
* link to the tickets that fully describe the issue and its acceptance criteria

For example, we know that save-as-you-go is functionality that existed in the VA version, we want to have hooks into in the generic version, but there's work to do to describe that feature and break it out into actionable issues.  On the other hand, we know that wrapping anything about identity management around forms is totally out of scope, so isn't a "feature gap" so much as it is "something we currently believe does not belong in a form creation library".

**Comment by jcmeloni-usds** [comment]
Assigning initially to @ju-liem and @fatimanoorva to:
* get this on the board
* prioritize
* assign as appropriate

**Comment by jcmeloni-usds** [comment]
@fatima-gov @bernars-usa Is there a tl;dr on where this was left?

**Comment by bernars-usa** [comment]
For features that we currently don't support but intend to investigate, I think we discussed linking to GitHub issues (perhaps as epics). For features we don't support and don't intend to support, like tables, it's not useful to document that we don't support them unless there are so many questions about it that it's becoming a burden to the team, but I'd argue even then, having the question and a decision documented in an issue is a more useful path forward because there are comments.

To move this forward, I would audit each item in the table to determine whether it's a feature we purposely don't support or intend to support later.
- For each feature we are open to supporting later, link to an issue. If one doesn't exist, create one.
- For features we don't intend to support, be explicit and concise about explaining why. This way, if someone wants to discuss the issue further, they can reference our reasons in a new issue and we can discuss it with them.

**Comment by jcmeloni-usds** [comment]
I looked at the wiki page and think it's fine as-is for where we are now.  When you get to Phase 2 planning, please take Sheri's comment (https://github.com/usds/us-forms-system/issues/108#issuecomment-422125498) into consideration and link to issues that you may create to address or aspirationally address the gaps.
