### ISSUE TITLE
Review and document component validation practices

### ISSUE THREAD

**Issue by dmethvin-gov** [usds/us-forms-system#114]
In reviewing [SelectWidget.jsx](https://github.com/usds/us-forms-system/blob/28aa7a63763763e2b86284c05cc380e0677310b6/src/js/widgets/SelectWidget.jsx) it's not clear exactly what validation guarantees widgets provide. When the result is supposed to be a number but is not, it returns a string. If the value in the select box is "Infinity" it returns the special `Number` value of `Infinity`. I suppose most of these might be caught later in validation but if that is the case I'm not sure why it attempts to do a conversion. 

Ideally the library should document what developer-users can expect from the component when there is invalid data. If this isn't documented, devs are likely to make assumptions that are incorrect and the library will need maintain those even though they weren't originally part of an API contract.

**Comment by ju-liem** [comment]
@dmethvin-gov Do you think this issue is basically handled with the Available Form Features and Usage Guidelines documentation (https://github.com/usds/us-forms-system/blob/master/docs/building-a-form/available-form-features-and-usage-guidelines.md) that the team has been putting together, or is further documentation/clarification needed?

**Comment by dmethvin-gov** [comment]
@ju-liem  What I see looks more like a bug and not something we would want to document. I'm not sure enough about that to tag it as a bug though, after the hackathon I'd like to discuss with @annekainicUSDS .

**Comment by jcmeloni-usds** [comment]
@dmethvin-gov @annekainicUSDS Did you two have a chat about this?  If so, what is the tl;dr?  Thanks!

**Comment by annekainicUSDS** [comment]
@jcmeloni-usds I haven't looked into this yet.

Something in general that I'd love to figure out how to manage is the balance between documenting status quo while knowing that we are making tons of changes to things all the time as the code is not yet totally stable. How should we prioritize documentation work against active development work, when that documentation work may soon be obsolete?

**Comment by bernars-usa** [comment]
> Something in general that I'd love to figure out how to manage is the balance between documenting status quo while knowing that we are making tons of changes to things all the time as the code is not yet totally stable.

This is a tricky thing to balance in any product. The question to ask yourself is whether or not people actively using the project? If so, you have a responsibility to keep the documentation up-to-date because users trust your documentation exactly up until the moment they don't, and then it's nearly impossible to get their trust back. To decide what should and should not be documented, ask yourself if the user will get reasonably tripped up if they don't have more information. You don't want to overwhelm with information that's obvious, which is why keeping the information you *do* include as succinct as possible is so important.

**Comment by annekainicUSDS** [comment]
Yep, great points @bernars-usa! I think at a minimum we should make sure the documentation is accurate and up to date with each release. It might be hard to keep things up to date between releases if we know things will be changing a lot, but as soon as new code is released, which is what the user will actually be interacting with, the documentation should accurately reflect that code. What do you think?

**Comment by bernars-usa** [comment]
> It might be hard to keep things up to date between releases if we know things will be changing a lot, but as soon as new code is released, which is what the user will actually be interacting with, the documentation should accurately reflect that code.

This sounds correct. As you're creating your release notes, you can use them to outline what your documentation gaps are, if any. It's always going to be easier on you to include documentation alongside your code changes whenever possible, though.

**Comment by dmethvin-gov** [comment]
I definitely think new things should have good documentation and testing. For the existing things that are lacking in those areas, I'm not inclined to go back and fix them until we know whether we want to keep them in their current form.
