### ISSUE TITLE
Accuracy in `ProgressBar` naming

### ISSUE THREAD

**Issue by fatima-gov** [usds/us-forms-system#159]
Cc: @bernars-usa @dmethvin-gov  

Related to open PR: https://github.com/usds/us-forms-system/pull/154

**Comment by bernars-usa** [comment]
Notes from our discussion today:

- https://github.com/usds/us-forms-system/blob/master/src/js/components/ProgressBar.jsx is actually for file upload progress.
- We currently don't support uploading files, so should we remove documentation for this component altogether for the time being?
- Once there's file upload capability, this component should be renamed to something like `FileUploadProgress`.

**Comment by dmethvin-gov** [comment]
For the purpose of the Hackathon I think this is fine as-is.  The `SegmentedProgressBar` isn't really configurable, form authors should just organize their chapters and pages to take advantage of its current behavior. They don't need to know its name.

**Comment by bernars-usa** [comment]
There's no published documentation about file uploads in https://github.com/usds/us-forms-system/blob/master/docs/building-a-form/available-form-features-and-usage-guidelines.md, so we're good to go on the first two bullets. What's left for this issue is to eventually think about the naming for `FileUploadProgress`.

**Comment by jcmeloni-usds** [comment]
@bernars-usa Is it still true that "what's left for this issue is to eventually think about the naming for `FileUploadProgress`"?

**Comment by bernars-usa** [comment]
Yes, that's still true. Not sure where that is in the team's priorities at all, though.

**Comment by jcmeloni-usds** [comment]
Cool cool.

**Comment by jcmeloni-usds** [comment]
@dmethvin-gov @annekainicUSDS is it true that what we're really talking about here is changing instances of naming from `ProgressBar` to something more contextually accurate, e.g. `FileUploadProgressBar`?  No functionality change?

(I ask because if that's the case, I'll just do it. :) )

**Comment by dmethvin-gov** [comment]
I think the reason it's confusing is that the [ProgressBar component](https://github.com/usds/us-forms-system/blob/master/src/js/components/ProgressBar.jsx) is "generic" and just renders the amount of progress that's passed as a percentage. However, the only place that we seem to use it is in file upload progress and I don't really think we need to document it? I guess it's possible someone might want to override what we do there but at the moment there's no way to override in any case. It's a little confusing because we also have a [SegmentedProgressBar](https://github.com/usds/us-forms-system/blob/ffd15c43556ab4108c1481b8d6163c8a1589a1ea/src/js/components/SegmentedProgressBar.jsx) that tells you how far done you are on the form. 

Looking at it from a future perspective, I think we can close this ticket because ProgressBar won't be exposed to users and `SegmentedProgressBar` will end up in the starter app.

**Comment by jcmeloni-usds** [comment]
Fair.
