### ISSUE TITLE
Intro page issues  

### ISSUE THREAD

**Issue by fatimanoorva** [usds/us-forms-system#160]
@bernars-usa @dmethvin-gov let's talk about this as a follow up to https://github.com/usds/us-forms-system/pull/154

Document that intro page and confirmation page are not included in the form itself. If embedding the form in an existing application, these aren’t available.

Cc: @usds/forms-system

**Comment by dmethvin-gov** [comment]
Also the Intro bug mentioned in the first bullet in #149 . There may be other things on that list that need docs or bug tickets.

**Comment by dmethvin-gov** [comment]
The intro bug in the starter app was fixed by https://github.com/usds/us-forms-system-starter-app/pull/15 but there is still the original question of whether this should be defined as a standard `pages` page rather than a React component. That fix to the starter app should actually work regardless, since the current code pushes the special-case intro page onto the routes as `/introduction` anyway.

**Comment by bernars-usa** [comment]
Both the intro and review pages are properly documented as described. @dmethvin-gov, do you need to move the information in https://github.com/usds/us-forms-system/issues/160#issuecomment-406045033 into a new issue for your tracking?

**Comment by dmethvin-gov** [comment]
@bernars-usa It's covered by #150 so it looks like this ticket is good to close.
