### ISSUE TITLE
Check `formConfig` sanity for better error detection

### ISSUE THREAD

**Issue by dmethvin-gov** [usds/us-forms-system#176]
Most of my time today has been spent exploring the error space of the project. Since so much of the information is deeply nested in `formConfig` it's surprisingly easy to make some mistake and get an error message that doesn't make a lot of sense. Mistakes in `schema` are diagnosed relatively well because the JSON Schema itself is validated. It does not appear that the rest of the config is checked.

One mistake that drove me crazy is that the name and route for each page *must* be unique, even when a page is in a different chapter. If there are duplicate names, the last page (possibly in a different chapter) wins and any earlier page definitions are ignored. There are no errors associated with this so it's even more confusing.

**Comment by jcmeloni-usds** [comment]
@dmethvin-gov I like it. Is this still a thing to do, or have other changes/clarifications throughout the code obviated the need for it?

**Comment by dmethvin-gov** [comment]
We still have quite a bit of work to do here.

**Comment by jcmeloni-usds** [comment]
Pushing to phase 2.

**Comment by cvalarida** [comment]
@dmethvin-gov brought up a great point in #282 about error checking bloating the production code. I think setting up guard rails for new developers using the library would be amazing, though. As @dmethvin-gov mentioned in that ticket, it could be a dev-mode-only kind of thing so it doesn't bloat production code with warnings that _should_ never get fired.

As far as whether it's a good idea to put up those guard rails as an established pattern, I think we can see a good precedent set by the React team. The guts of that library is silly complicated, but we don't have to understand how it all works because when we break a thing, the error messages we're shown usually point us in the right direction.

I've been using this library for a little over a year and a half, since it was first conceived back on vets-website and I _still_ run into quirks that I have to spend some time running down, only to discover I did a Dumb Thing™. The ramp-up time for new developers using the library would be drastically reduced if we had solid error messages catching common mistakes. Ultimately, I believe that will lead to wider adoption since, in my opinion, ramping up is the biggest challenges most teams will face when using this excellent library.

Wherever we end up on this, I'm super excited to see it get there! It's been awesome to see it grow this far. Y'all are doing great work! :raised_hands:

**Comment by dmethvin-gov** [comment]
I like what React does as well, it's a nice pattern to follow. 👍

**Comment by dmethvin-gov** [comment]
We don't have plans to add more error checking so I'll close this. In general it's a good idea but the ticket as-is doesn't have specifics about how that would be done.
