### ISSUE TITLE
Let's talk about the `hideOnReviewIfFalse` property

### ISSUE THREAD

**Issue by bernars-usa** [usds/us-forms-system#179]
Over in https://github.com/usds/us-forms-system/pull/174#discussion_r203721196, we had a discussion about the `hideOnReviewIfFalse` property (mentioned in https://github.com/usds/us-forms-system/blob/master/docs/building-a-form/available-form-features-and-usage-guidelines.md#usage-guidelines-13). From @dmethvin-gov:

> Is "the specified field" the same field as "the field value"? For example if I have a checkbox with a title on it, does this hide the title in the review page unless it's checked?

From @annekainicUSDS:

> Sorry no, when I said "specified field" I did not mean the "field value", but the field itself. Yes, if this property is passed as `true`, it hides the entire field from the review page.

This is *extremely* difficult to document, which is usually a sign we need to think about the implementation.

@usds/forms-system

**Comment by jcmeloni-usds** [comment]
@bernars-usa Please confirm we still need to think about this for clarity in documentation.  Thanks!

**Comment by bernars-usa** [comment]
> Please confirm we still need to think about this for clarity in documentation.

It's not really that we need to clarify the docs here, it's that the property itself has a less-than-optimal name (from my understanding, you can set `hideOnReviewIfFalse` to `true`, and if it's `true`, it hides... something... from the review page).

**Comment by annekainicUSDS** [comment]
Yes, what this property is used for is let's say we have a field called `isANerd`, and the user answered that question "No", so the value of that field is `false`. On the review page, when we come to the page where that question was originally asked, we would not show the question at all because it is not relevant to the user. The default is to show all questions that were asked, regardless of the answer or if they are blank. This gives us the ability to hide a question that has a value of `false` if we want to.

If anyone can come up with a better name for this feature, let me know!

**Comment by dmethvin-gov** [comment]
The review page is basically a second, completely different UX of a form filler with a potentially different set of widgets, different presentation, different editing approach, etc. It could almost be used on its own as a single-page interface to USFS, except that we're depending on the form to be valid on entry. However, we know that's a constraint we want to get rid of anyway.

It might be worth looking a little deeper at the UX of the review page regarding how it displays checkboxes and Yes/No questions. The way it converts a checked box to True and unchecked boxes to False (but doesn't show the False) is a bit confusing. It almost looks on the review page as if I am making statements that don't apply in my case because the checkbox next to the statement isn't there.

It would be easier to show this if I could post a screenshot, but I can't do that from my WHIT laptop.

**Comment by jcmeloni-usds** [comment]
Noting for the record -- Dave & I talked through this in person w/ pointing at a screen.

**Comment by jcmeloni-usds** [comment]
Just following up here -- I'm closing this as wont-fix, basically, because:
1) it's actually indicative of a bigger UX issue that I think will get sorted out in phase 2 discovery
2) changing anything will screw up vets.gov, so if they've got a way through this right now, keep doing it.
