### ISSUE TITLE
The `initialData` possibly broken and incorrectly documented?

### ISSUE THREAD

**Issue by dmethvin-gov** [usds/us-forms-system#185]
I've been trying to define an initial data value using `initialData` and having no success. The [unit test](https://github.com/usds/us-forms-system/blob/c8a3f3442ed74940a64b700e1d638d3b9977710e/test/js/state/index.unit.spec.js#L23) indicates that `initialData` should be at the `page` level and there is an [assertion](https://github.com/usds/us-forms-system/blob/c8a3f3442ed74940a64b700e1d638d3b9977710e/test/js/state/index.unit.spec.js#L47) but that assertion does not ensure the data actually appears in the form field. If I put a breakpoint on `React.createElement` I can see that no `value` is being passed. 

Separately, the one of the docs pages that mentions `initialData`, [quick-start-example-formjs-file.md](https://github.com/usds/us-forms-system/blob/0644d6d03fb17891b8e13ca84287180f8d079149/docs/building-a-form/quick-start-example-formjs-file.md), puts it in the wrong place if the unit test is to be believed. The only other mention is in [common-patterns-for-building-forms.md](https://github.com/usds/us-forms-system/blob/9c2752823e1fe0fb59bb05671f3d123386ef8170/docs/building-a-form/common-patterns-for-building-forms.md) which is correct but kind of a degenerate case and not covered in the text.

Normally I'd create separate code-bug and docs tickets but it's not completely clear which is wrong.

**Comment by dmethvin-gov** [comment]
The chunk of `pageConfig` looks like:
```js
    TESTSECTION: {
      title: 'I am a testy section',
      pages: {
        SPECIAL: {
          path: 'BORKEN',
          title: 'Test thingy',
          initialData: { startdate: 'ha'},
          schema: {
            type: 'object',
            properties: {
              startdate: { type: 'string' }
            }
          },
          uiSchema: {
          }
        }
      }
    }
```

**Comment by annekainicUSDS** [comment]
Yes, the example is quick-start-example-formjs-file.md is a little misleading because everything nested under `pages` should actually be nested like this: `pages: { page: { path: 'some-path', ... } }`. So you're right that that example is wrong and that `initialData` should nested within a particular `page`. Here's an example from a Vets.gov form of what it looks like: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/edu-benefits/1990/config/form.js#L211.

However, I'm not really sure why you're running into issues otherwise. The code sample you included looks correct. Is there a branch or something I can pull down to see this and do a bit of debugging myself?

**Comment by dmethvin-gov** [comment]
I can't tell what's different but this example works.

```js
    TESTSECTION: {
      title: 'I am a test section',
      pages: {
        SPECIAL: {
          path: 'test',
          title: 'Test of initialData',
          initialData: {
            simple: 'initial data'
          },
          schema: {
            type: 'object',
            properties: {
              simple: { type: 'string' }
            }
          },
          uiSchema: {
          }
        }
      }
    }
```
