### ISSUE TITLE
Update "Quick Start" page with better getting started examples

### ISSUE THREAD

**Issue by dmethvin-gov** [usds/us-forms-system#199]
The [current quick start page](https://github.com/usds/us-forms-system/blob/3261c6a32a802856341a5eddf006429fa1457f86/docs/building-a-form/quick-start-example-formjs-file.md) is just a giant form.js file that has all possible options. I think we want to document all these in reference docs if they're not already, but the Getting Started seems like it should begin with simpler examples. Either that or we direct people to the tutorial?

Pulled from the Hackathon feedback in #190 .

**Comment by jcmeloni-usds** [comment]
@bernars-usa Have we changed anything about the quick start page or shall I consider it a thing for me to do? Thanks!

**Comment by bernars-usa** [comment]
We haven't updated the Quick Start at all since before the hackathon, no. This is another example of a reference docs task that shouldn't use up a huge time investment if the library is going to change significantly (see https://github.com/usds/us-forms-system/issues/200#issuecomment-422137778 for more on that discussion).

**Comment by jcmeloni-usds** [comment]
ok thanks!  i'll give it another quick look.

**Comment by jcmeloni-usds** [comment]
I gave this a quick look per my comment above, but agree with Sheri that it should be revisted _after_ any big changes in a 2.x release happen. I think it's a fine quick start as-is, and the addition of several exemplar forms also provides context/examples.
