### ISSUE TITLE
Get access to full formData in validators

### ISSUE THREAD

**Issue by markgreenburg** [usds/us-forms-system#224]
**Is your feature request related to a problem? Please describe.**
validation functions aren't always passed the full `formData` in arguments.

**Describe the solution you'd like**
I'd like to be able to access all of the formData in any validator so that we can make validations against arbitrary pieces of form data regardless of where we currently are in the schema.

**Describe alternatives you've considered**
Restructuring our schema - this doesn't work because fundamentally, we still need to use array-pages, and aren't able to get to formData outside of the current array index's formData

calling updateSchema and shoving the servicePeriods info in there so that we can access it later. This doesn't work because at the point where we have servicePeriod data, we don't yet know what pages we'll need to make (varies based on veteran input), and consequently have nowhere to shove the servicePeriod data. 

**Steps to reproduce**
1. Check out the `526-fix-treatment-validations-mg` branch from `vets-website`
2. Start up the vets-website app and vets-api (we'll need to log in)
3. Navigate to the form at `/disability-benefits/apply/form-526-disability-claim`
4. Log into vets.gov (will share test creds for this form in slack)
5. Start the form
6. Ensure data exists or that you fill it out for the service periods screen
7. Select a disability from the list when prompted.
8. Choose 'va medical records' from the list of supporting evidence types
9. Open up dev console
10. Advance to page where you're asked for your treatment facility info
11. See what gets logged in the console for `formData`

**Context**
To see how this works, please reference the schema / uiSchema in `vets-website/src/applications/disability-benefits/526EZ/pages/treatmentSchema.js` as well as the related validator in the helpers file at `vets-website/src/applications/disability-benefits/526EZ/helpers.jsx`
I've added some comments to the code there

**Comment by dmethvin-gov** [comment]
You can link directly to the code, [are these the comments you meant](https://github.com/department-of-veterans-affairs/vets-website/blob/3f77f415c2619194cb6bd0f7bb43b9a5df5e6705/src/applications/disability-benefits/526EZ/helpers.jsx#L161-L169)? You're saying this function is called at `transformForSubmit` time and thus some non-submittable info has been stripped out from the actual form? I did a [repo search](https://github.com/department-of-veterans-affairs/vets-website/search?q=transformdisabilities&unscoped_q=transformdisabilities) but couldn't determine where it was called, maybe the branch isn't indexed yet.

**Comment by dmethvin-gov** [comment]
Hmmm, it's using prefillTransformer which us-forms-system doesn't implement. Nevertheless I'm interested in understanding this use case.

**Comment by markgreenburg** [comment]
@dmethvin-gov sorry for the confusion - the comments I'm talking about are at https://github.com/department-of-veterans-affairs/vets-website/blob/3f77f415c2619194cb6bd0f7bb43b9a5df5e6705/src/applications/disability-benefits/526EZ/helpers.jsx#L977

This validator fires on the treatments page in my branch: https://github.com/department-of-veterans-affairs/vets-website/blob/3f77f415c2619194cb6bd0f7bb43b9a5df5e6705/src/applications/disability-benefits/526EZ/pages/treatmentSchema.js#L70

This schema is imported into the full form config and used like so on the VA Treatment Facilities page:
https://github.com/department-of-veterans-affairs/vets-website/blob/3f77f415c2619194cb6bd0f7bb43b9a5df5e6705/src/applications/disability-benefits/526EZ/config/form.js#L457

Does that help?

**Comment by markgreenburg** [comment]
Oh, by the way, here's the uiSchema for the formData that I'd like to validate the fieldData against:
https://github.com/department-of-veterans-affairs/vets-website/blob/3f77f415c2619194cb6bd0f7bb43b9a5df5e6705/src/applications/disability-benefits/526EZ/config/form.js#L200

**Comment by dmethvin-gov** [comment]
Yes, it does!

I would lean towards these kinds of validation being done as part of a global validation method that can "see" all the data at once, rather than inside a field-specific one. At the global level you could expect to have access to everything and can cross-check whichever fields you'd like.  It could also address "back-reference" or "circular-reference" validation issues across pages. From a UX experience I'd think a form design should avoid these like the plague but there may be cases where it can't be avoided.

The problem with that is that currently we expect all validation to have already been performed by the time the user gets to the submit button, and we don't have a way to display errors effectively. Non-linear forms like the SF-86 have a "final review" step where there would be the chance to look for these kinds of inconsistencies.

Sooo, I guess we'd need to throw another argument on the end of the calls we make in [uiSchemaValidate](https://github.com/usds/us-forms-system/blob/91558c035822660775fe04c3f44edf104a6c1b06/src/js/validation.js#L120) to give a field validator full `formData` access?

**Comment by jbalboni** [comment]
The forms on vets.gov try to notify users as soon as possible when someone that's been entered needs to be corrected. Waiting until the end of a form to give the user a list of things to go back and fix seems like a less than optimal experience. I could see a form getting too complex for that to be possible, but it seems like something we want to avoid if we can, rather than the recommended approach.

Sadly, I think adding another parameter to `uiSchemaValidate` is probably the easiest approach for now. I had actually intended for validators to have access to the entire form data; it's the fourth parameter to `uiSchemaValidate`, which is passed to validator functions. But for array pages the "full" form data that's passed to `FormPage` is the particular item in the array that page is on. Ideally we would change that existing parameter to have the real full form data all the time, but that would probably break a bunch of forms and I'm not sure how to detect that.

**Comment by dmethvin-gov** [comment]
I've got a proposed PR in #290, please take a look and let me know if there might be a better way!

In a later version I'd like to explore having a validation function declare what fields it needs to do its checks. Right now `recalculateSchemaAndData` runs on every user keystroke and processes the entire form. These functions that have access to the entire form for validation or conditional display can be looking at anything so they need to be called when anything changes. My computer hits 15-20% cpu load just while typing into the 1990 form.
