### ISSUE TITLE
Refactor `stringifyFormReplacer` helper function into more modular functions

### ISSUE THREAD

**Issue by erikphansen** [usds/us-forms-system#259]
**Is your feature request related to a problem? Please describe.**
The [`transformForSubmit`](https://github.com/usds/us-forms-system/blob/master/lib/js/helpers.js#L382) helper function defaults to use the [`stringifyFormReplacer`](https://github.com/usds/us-forms-system/blob/master/lib/js/helpers.js#L336) when processing form data for submission. The processing in `stringifyFormReplacer` performs a lot of magic and could likely have unintended side effects. This actually did happen while adding a new feature in vets.gov. [This line](https://github.com/usds/us-forms-system/blob/master/lib/js/helpers.js#L338) in particular was responsible for stripping out a valid address object, leading to a lot of confusion when trying to figure out why the correct payload wasn't getting sent to the backend service.

**Describe the solution you'd like**
Perhaps the functionality in `stringifyFormReplacer` could be broken out into smaller parts and `transformForSubmit` could opt in to only the processing the user wanted. That's just a suggestion.

**Additional context**
I chatted with @annekainicUSDS about this on September 10, 2018. She determined that this particular code has been in use for a long time and is likely a relic from the original HCA on Vets.gov. It's possible that forms actually depend on this JSON transformation, so any solution would have to avoid breaking forms that are calling this function.

**Comment by dmethvin-gov** [comment]
I'm working on #211 which is trying to address some of the same concerns regarding site-specific features and behaviors.  There shouldn't be a global utility function that [knows about the data representations of certain widgets and changes them](https://github.com/usds/us-forms-system/blob/master/src/js/helpers.js#L245-L249), at least not at the USFS level. (Also note that we don't currently have any widgets or definitions specific to fields with the name `address` so this is especially magic right now.) If we need that sort of functionality in a generic way the widget itself should be doing the transformation, or if it's site-specific the USFS caller should be doing the transformation. 

Users can affect the submit process by using `formConfig.transformForSubmit` or get even more control with [`formConfig.submit`](https://github.com/usds/us-forms-system/blob/f40fe509e53372ab61d79ee631947dd6b0132204/src/js/actions.js#L146). 

As part of #211 I have to pull out the [vets-specific server responses](https://github.com/usds/us-forms-system/blob/f40fe509e53372ab61d79ee631947dd6b0132204/src/js/actions.js#L159-L166) and this issue involves wanting to change [the call to `transformForSubmit`](https://github.com/usds/us-forms-system/blob/f40fe509e53372ab61d79ee631947dd6b0132204/src/js/actions.js#L148-L150) so it does transformations differently (but only in some cases). The only other thing `submitForm` does is actually submit the form, and [several things there are also specific to vets.gov servers](https://github.com/usds/us-forms-system/blob/f40fe509e53372ab61d79ee631947dd6b0132204/src/js/actions.js#L123-L129) that need to be changed as part of #211 as well. 

Once the fix for #211 lands it seems like `formConfig.submit` will need to be used anyway and maybe an internal `transformForSubmit` isn't needed? The alternative would seem to involve a lot of hooks and `formConfig` settings to do the right things at the right time (transform the data based on the server's requirements, set server-specific headers, process server-specific responses, etc.). We can always provide samples of what a `formConfig.submit` looks like for various cases.

**Comment by dmethvin-gov** [comment]
I'm merging this into #211, the `stringifyFormReplacer` will only remove empty arrays and objects now. If there are widgets that need post-processing they would need to be processed outside USFS.
