### ISSUE TITLE
Description displays twice when showFieldLabel is true for object type schemas

### ISSUE THREAD

**Issue by cehsu** [usds/us-forms-system#260]
**Describe the bug**
Description displays twice when showFieldLabel is true for object type schemas.

This can be resolved by setting showFieldLabel to false, for fields that don't involve any validation, but this is problematic for required fields or fields with validation logic, as the field label indicates that the field is required, and displays error messages when the field is invalid.

**To Reproduce**
Require an object in the schema, and assign a title and description, as well as set `showFieldLabel: true`, in 'ui:options'.

**Expected behavior**
Description should display as often as and along with the label.

One option is to update ObjectField:
```
          {CustomTitleField && !showFieldLabel
            ? <CustomTitleField
              id={`${idSchema.$id}__title`}
              formData={formData}
              formContext={formContext}
              required={required}/> : null}
          {!CustomTitleField && title && !showFieldLabel
            ? <TitleField
              id={`${idSchema.$id}__title`}
              title={title}
              required={required}
              formContext={formContext}/> : null}
          {textDescription && !showFieldLabel && <p>{textDescription}</p>}
          {DescriptionField && !showFieldLabel && <DescriptionField formData={formData} formContext={formContext} options={uiSchema['ui:options']}/>}
          {!textDescription && !showFieldLabel && !DescriptionField && description}
```

**Screenshots**
showFieldLabel: true
![image](https://user-images.githubusercontent.com/16051172/45391075-98717000-b5d6-11e8-8264-fc91d6bbd96c.png)

showFieldLabe: false
![image](https://user-images.githubusercontent.com/16051172/45391073-94455280-b5d6-11e8-9d35-5c7b22f19d26.png)

**Additional context**
Kindly refer to this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/8377) for additional context.

**Comment by dmethvin-gov** [comment]
Here is a minimal live repro: https://codesandbox.io/s/p78zj18jwx

**Comment by dmethvin-gov** [comment]
Well @cehsu I think you answered a question regarding a problem with #252 that I'm building! It has a similar situation and I didn't know why the validation wasn't showing even though validation was definitely happening.

I don't really understand this well enough to know the best solution, maybe @annekainicUSDS has some thoughts.

**Comment by cehsu** [comment]
That's good to hear @dmethvin-gov !

Perhaps we should rename `showFieldLabel` --> `showFieldLabelAndDescription` and update how this is used as described [here](https://github.com/usds/us-forms-system/issues/260#issue-359248804).

**Comment by annekainicUSDS** [comment]
Hi @cehsu! I took a look at this issue by looking at the code and running your branch locally, and I want to make sure I understand _why_ this bug is happening. Here's what I think I know so far:

For the field is question ("Which topic best describes your feedback?"), what ends up being rendered is a `<FieldTemplate/>` wrapped around an `<ObjectField/>`. Both components have logic in them to render the `['ui:description']` text, which is why this text is being rendered twice.

I see how your suggestion is to repurpose `showFieldLabel` to now be used to control not just the label but also the description text. I guess I have 2 concerns with this:
1. Will this create unintended consequences? `showFieldLabel` is already used widely across Vets.gov; will we inadvertently be hiding description text when we don't mean to be?
2. Is this the right solution for this problem? It seems like the root of the problem is that there are 2 separate components that are both responsible for rendering the same thing, and sometimes these components are used together, so that thing will be rendered twice. Is there a more direct way of solving this problem?

I'm not sure of the solution yet, would need to do some more digging, but wanted to raise these concerns first to see what you think!

**Comment by dmethvin-gov** [comment]
Good diagnosis! I noticed that a `FieldTemplate` and `ObjectField` both used the description but didn't realize the latter was being wrapped in the former.

If the description was being passed via props we could just have the outer component remove it before passing props down. In this case it's looking at the `uiSchema` directly so I guess that won't work. I can think of some other ways to do this, for example define a `ui:objectDescription` that takes priority over `ui:description` for `ObjectField`. That seems hacky though.

To Anne's point, does it seem right (from a design standpoint) that `ObjectField` is wrapped in `FieldTemplate`? They have similar logic using the same properties, [here's ObjectField](https://github.com/usds/us-forms-system/blob/master/src/js/fields/ObjectField.jsx#L194-L211) and [this is FieldTemplate](https://github.com/usds/us-forms-system/blob/master/src/js/components/FieldTemplate.jsx#L85-L93).

**Comment by dmethvin-gov** [comment]
Since the two calls pass different props, you could have a `Description` component that renders differently depending on its props: https://codesandbox.io/s/p78zj18jwx

Again, this doesn't feel like the "right" solution but it would cause the least disruption. A design change like not wrapping `ObjectField` with `FieldTemplate` might be the right way but seems more likely to break existing vets.gov forms.

**Comment by cehsu** [comment]
Thanks @dmethvin-gov, we will go with your recommendation of using the props to determine whether the description is shown.

Since the FieldTemplate title displays the validation messages, it might make sense to default to using that, rather than the ObjectField title.

**Comment by jcmeloni-usds** [comment]
@dmethvin-gov @annekainicUSDS My reading of this is a won't-fix -- correct?

**Comment by dmethvin-gov** [comment]
It looked to me like the symptom of a deeper design issue that Anne mentioned above, but there's a workaround for now. If we want to tackle this it would most likely be a breaking change for something out there so we'd need to wait for a major release.

**Comment by dmethvin-gov** [comment]
There's a workaround mentioned above, which should be fine for now.
