### ISSUE TITLE
Currency widget accepts values out to three decimal places

### ISSUE THREAD

**Issue by cehsu** [usds/us-forms-system#269]
**Describe the bug**
The currency widget accepts values out to three decimal places.

**To Reproduce**
Enter a value out to three decimal places into a currency field.

**Expected behavior**
The validation message should be provided for invalid values.

**Screenshots**
![image](https://user-images.githubusercontent.com/16051172/45642500-33ea6100-ba6d-11e8-8e7e-291400a29b1d.png)

**Additional context**
We are temporarily solving this by adding the following validation:

```
export function validateCurrency(errors, currencyAmount, formData) {
  // Source: https://stackoverflow.com/a/16242575
  if (!/(?=.*?\d)^\$?(([1-9]\d{0,2}(,\d{3})*)|\d+)?(\.\d{1,2})?$/.test(currencyAmount)) {
    errors.addError('Please enter a valid dollar amount');
  }
}
```

**Comment by dmethvin-gov** [comment]
It seems intentional because [there is a test for this very thing](https://github.com/usds/us-forms-system/blob/95c6518d5a0cc3a40f7376840760026b16007e13/test/js/widgets/CurrencyWidget.unit.spec.jsx#L88-L101)! I don't see any test at all for currency validation so perhaps it was supposed to have been caught there. 

There is a [strange validation on change](https://github.com/usds/us-forms-system/blob/95c6518d5a0cc3a40f7376840760026b16007e13/src/js/widgets/CurrencyWidget.jsx#L19-L36) that I don't understand. Although it goes through all sorts of hoops to check the format of the data, it *always* calls `onChange` regardless, with whatever possibly invalid data is in the field. The only case that is cleaned up at all is when there are [stray characters in an otherwise valid amount](https://github.com/usds/us-forms-system/blob/95c6518d5a0cc3a40f7376840760026b16007e13/src/js/widgets/CurrencyWidget.jsx#L29). I think that is what the unit test above is ensuring. This isn't the only widget with this behavior, I noticed it in #114 as well.

Just to be sure we're in agreement as far as point of validation is concerned, the expected behavior is to validate this when the "Next" button is clicked, correct? It would still be possible to take a screen shot similar to the one above but the form should show an error when the user tried to move to the next page.

**Comment by annekainicUSDS** [comment]
@cehsu I'm unable to recreate this bug :/ When testing this on HCA, I'm able to trigger an error when entering three decimal places:
<img width="448" alt="screen shot 2018-09-24 at 1 36 05 pm" src="https://user-images.githubusercontent.com/25183456/45968419-e5097200-bffe-11e8-8b67-924b6d1616c1.png">

This question is using the `<CurrencyWidget>` as well. I'm wondering what could be different in the example that you provided from the example I was using?

**Comment by annekainicUSDS** [comment]
Oh, that additional validation function is already being applied to HCA, oops! Digging into this more, I have the same confusion as Dave, that the `handleChange` function in the `<CurrencyWidget/>` has [a regex](https://github.com/usds/us-forms-system/blob/master/src/js/widgets/CurrencyWidget.jsx#L25) already that should catch more than two decimal places, yet is updating the value anyway. My guess is that this function is not meant to catch errors, but rather update the form data in a format that can be updated. The errors are applied later after the field's value has been updated in state.

My understanding right now is that there are two ways to validate an input:
1. The JSON `schema` itself
2. Additional validation functions passed to the `uiSchema`

The only validation being run on currency fields (without the additional function you've created on the Vets.gov side) is the schema validation, which simply checks if the input is a number. There are no additional validation functions passed to the `uiSchema` that would catch this kind of error. 

Sounds like the function you created on the Vets.gov should be passed to the `uiSchema` in the definition for `currency`. What do you all think?

**Comment by annekainicUSDS** [comment]
Great, I can take this on!
