### ISSUE TITLE
AutosuggestField to fall back to empty array on query 

### ISSUE THREAD

**Issue by cvalarida** [usds/us-forms-system#282]
**Describe the bug**
This is an old one, so I may not remember all the specifics, but I'll put down what I _do_ remember.

Context:
- We have an autosuggest field that uses a callback to get the list of results.
- The autosuggest field we have also supports entering free text

When writing the `queryForResults` callback for `AutoSuggestField`, I have to `return []`, otherwise it breaks the field because it expects an array, but gets `undefined`.

I thought about throwing an error in the failure handling section of the callback or in the `AutosuggestField` itself, but decided against it because if the field also accepts free text, it should take the input that resulted in a failed call to get suggestions.

We originally filed a ticket for vets-website because of the discussion in [this PR comment](https://github.com/department-of-veterans-affairs/vets-website/pull/7839#discussion_r194123218).

**To Reproduce**
1) Create a field as described in the context above
2) For the callback, don't make it return anything (or return `undefined`)

If I recall the issue correctly, it'll break when `undefined` finally gets passed to [`sortListByFuzzyMatch`](https://github.com/usds/us-forms-system/blob/master/src/js/fields/AutosuggestField.jsx#L96).

**Expected behavior**
If the callback doesn't return anything, I think it makes sense to use an empty array by default.

**Additional context**
This hasn't affected us in a while, but we know the nuance of this particular field. It might be confusing for new teams using the field to get an error because they returned `undefined` (or some other data type that will break).

Maybe changing [this line](https://github.com/usds/us-forms-system/blob/master/src/js/fields/AutosuggestField.jsx#L83) might do the trick:
```js
getOptions(inputValue).then(results => this.setOptions(results || []));
```
Ideally, we'd have some invalid data catching to help developers:
```js
getOptions(inputValue).then(results => {
  if (results && !Array.isArray(results)) {
    throw new TypeError(`Expected an array, but got ${typeof results}`);
  }
  return this.setOptions(results || []);
});
```

**Comment by dmethvin-gov** [comment]
The implementer of `getOptions` should be returning an array, it's risky to silently turn bad data into good.  If we think this is truly going to be a *common* mistake we can check for a bad return value at call time as mentioned above. It might be worth looking at all the places where things like this happen and consider whether we want to have a consistent set of runtime type checks. Ideally if we were using TypeScript we could just define the function to return an array and it would give an error at build time without us having to add code.

**Comment by cvalarida** [comment]
Static type checking would be awesome. It's been something we've been discussing on vets.gov for a while now, actually.

:thinking: Now that I think about it, though, _would_ it catch the error? It'd be on the app side, not the library side, and the app would use the compiled JS in `lib/`, so would we get the benefit of static type checking when we actually implement the callback? The alternative would be to use the TS in `src/` and compile all that, but is that a reasonable expectation for apps using the library? (Genuine question; I've never used TS or Flow myself.)

At any rate, that ticket looks like a good umbrella ticket to discuss the larger implications of providing warning messages to developers. I'll drop a comment in there about the devmode-only bit.

Thanks for your thoughts on this, @dmethvin-gov!

**Comment by dmethvin-gov** [comment]
When you're using a compiled version of the USFS library, it would have something like a `usfs.d.ts` file that you include with all its types. If the `getOptions` function that you provided to the widget didn't return an array in all its return paths, you'd get an error during compile. 

The problem usually comes during the transition to TypeScript because all of us don't tend to be very concerned about types in JavaScript, so we often assume we know the types. [Looking at this code](https://github.com/department-of-veterans-affairs/vets-website/blob/38f9c13119feb7f5a525be224b2e167f4a225a5e/src/applications/disability-benefits/526EZ/helpers.jsx#L623-L631), the error case is clear since you explicitly return an empty array. 

The success case is fuzzier because [apiRequest can return almost anything](https://github.com/department-of-veterans-affairs/vets-website/blob/38f9c13119feb7f5a525be224b2e167f4a225a5e/src/platform/utilities/api/index.js#L12) so  if you define `response.data` as type `any` you would need to check the return value to ensure it actually gave you an array--or just blow up when it can't find the `map` method. 😸 

Blowing up isn't that bad of an option since if you have a global error handler hooked into RavenJS the stack trace will point you to this line and you'll think, "Huh, why didn't `response.data` have a `map` method?" and figure it out from there. Notice that happens before you call USFS so it doesn't really matter what we do in the library--USFS isn't even called because of the error.

**Comment by dmethvin-gov** [comment]
We'll track the improved error handling in #176, thanks!
