### ISSUE TITLE
Allow option to set all chapters as open by default on review page

### ISSUE THREAD

**Issue by briaguya** [usds/us-forms-system#330]
**Is your feature request related to a problem? Please describe.**
The City of Austin form for the Office of Police Oversight has been designed with the review page having all of the chapters expanded upon load - https://github.com/cityofaustin/techstack/issues/975. 

**Describe the solution you'd like**
Instead of trying to inject some javascript or override some styling, it seems to make the most sense to go ahead and set the openChapters on the initialState to include all current chapters.

**Describe alternatives you've considered**
Instead of needing to know all of the chapter keys in the chapters object from the config, reworking the setting of initial open state for chapters in a way that respects a global flag. Also hacking together some code outside of making changes to usfs to simulate the effect.

**Additional context**

**Comment by dmethvin-gov** [comment]
As far as the technical part goes, I think the approach proposed in #331 looks fine. I'd be fine with merging it.

For a relatively small form though, I wonder if it even makes sense to have a review page at all. There's no option to avoid one. Essentially, the review page is just another way to edit the exact same schema, so we have two different form editing UX for each form. Does this form benefit from a review page?

I get the feeling that the current review page was an answer to the problem of how to edit previous pages in a linear navigation design. As soon as we get to non-linear navigation there's not much benefit to in-place editing since they can easily go back to the original page. That would seem less confusing than presenting them with a different editing view of the same data they entered earlier.

**Comment by dmethvin-gov** [comment]
Implemented by #331
