### ISSUE TITLE
Determine the top 20 most commonly used Fed. Gov. forms

### ISSUE THREAD

**Issue by ButtersUSDS** [usds/us-forms-system#40]
Based on daily data pulled from analytics.usa.gov.

This would be used to determine exemplar forms at the least. At best, it would lead to a form in production, built by the agency.

**Comment by kaschm-usds** [comment]
Did an analysis of four (random) days of analytics data over a month to determine most top accessed forms by volume. May over-index a bit towards IRS due to tax season. Thx to @ju-liem for pulling data. 

Top 20 forms are as follows:

| By Volume | Agency | Form Name | Human Name  | URL|
| ------------- | ------------- | ------------- | ------------- | ------------- |
| 1 | DOS | DS-11 | Passport Application | https://eforms.state.gov/Forms/ds11.pdf|
| 2 | USCIS  | I-9 | Employment Eligibility Verification | https://www.uscis.gov/system/files_force/files/form/i-9.pdf|
| 3 | USCIS  | I-130 | Petition for Alien Relative | https://www.uscis.gov/system/files_force/files/form/i-130.pdf|
| 4 | USCIS  | I-765 | Application for Employment Authorization | https://www.uscis.gov/system/files_force/files/form/i-765.pdf|
| 5 | USCIS  | N-400 | Application for Naturalization | https://www.uscis.gov/system/files_force/files/form/n-400.pdf|
| 6 | USCIS  | I-864 | Affidavit of Support Under Section 213A of the INA | https://www.uscis.gov/system/files_force/files/form/i-864.pdf|
| 7 | USCIS  | I-485 | Application to Register Permanent Residence or Adjust Status | https://www.uscis.gov/system/files_force/files/form/i-485.pdf|
| 8 | IRS | W-4 | Employee’s Withholding Allowance Certificate | https://www.irs.gov/pub/irs-pdf/fw4.pdf|
| 9 | IRS | W-9 | Request for Taxpayer Identification Number and Certification | https://www.irs.gov/pub/irs-pdf/fw9.pdf|
| 10 | IRS | 4506-T | Request for Transcript of Tax Return | https://www.irs.gov/pub/irs-pdf/f4506t.pdf|
| 11 | Education | PSECF - XBCR | Public Service Loan Forgiveness (PSLF): Employment Certification Form | https://studentaid.ed.gov/sa/sites/default/files/public-service-employment-certification-form.pdf|
| 12 | USCIS  | I-751 | Petition to Rremove Conditions on Residence | https://www.uscis.gov/system/files_force/files/form/i-751.pdf|
| 13 | IRS | 1040 | U.S. Individual Income Tax Return | https://www.irs.gov/pub/irs-pdf/f1040.pdf|
| 14 | SSA | SS-5 | Application for a Social Security Card  | https://www.ssa.gov/forms/ss-5.pdf|
| 15 | USCIS  | I-131 | Application for Travel Document | https://www.uscis.gov/system/files_force/files/form/i-131.pdf|
| 16 | CMS | CMS 40B-E | Application for Enrollment in Medicare Part B | https://www.cms.gov/Medicare/CMS-Forms/CMS-Forms/Downloads/CMS40B-E.pdf|
| 17 | USCIS  | G-28 | Notice of Entry of Appearance as Attorney or Accredited Representative | https://www.uscis.gov/system/files_force/files/form/g-28.pdf|
| 18 | DOS | DS-82 | U.S. PASSPORT RENEWAL APPLICATION FOR ELIGIBLE INDIVIDUALS | https://eforms.state.gov/Forms/ds82.pdf|
| 19 | IRS | 941 | Employer’s QUARTERLY Federal Tax Return | https://www.irs.gov/pub/irs-pdf/f941.pdf|
| 20 | USCIS  | G-1145 | e-Notification of Application / Petition Acceptance  | https://www.uscis.gov/system/files_force/files/form/g-1145.pdf|

**Comment by jcmeloni-usds** [comment]
@mattcutts-gov The appearance of the SSA form on this list piqued my interest -- how about you?
