### ISSUE TITLE
Make a Forms Best Practices Outline

### ISSUE THREAD

**Issue by ButtersUSDS** [usds/us-forms-system#42]
This will be living (like all the things), and will change the more research is done, but we should start capturing the already known learnings.

- [ ] Comparative research (see research strategy in wiki)
- [ ] Document on wiki

**Comment by jcmeloni-usds** [comment]
@ju-liem I am of the mind that we don't need to create a forms best practices guide but we should create documentation around why we have created what we have created and why, and also some starting points for thinking about how to create a better/frictionless form experience online (vs pdf).  Can you take care of that please?  Thanks!

**Comment by jcmeloni-usds** [comment]
@bernars-usa Please see my comment above.  Would you agree with my assertion, or not? Or other thoughts?  What does your gut tell you?  Thanks!

**Comment by bernars-usa** [comment]
> I am of the mind that we don't need to create a forms best practices guide

I agree with this. There are many articles and blog posts online describing best practices for online forms. It might be useful to gather some of the better ones on the wiki (I think I shared this recent one I loved: https://www.invisionapp.com/blog/designing-online-forms/).

> ... we should create documentation around why we have created what we have created

I think expanding on the "[About this project](https://github.com/usds/us-forms-system#about-this-project)" information in the library's README could be a useful tool for getting people investigating a solution to paper/PDF forms to consider this project (that information was culled from the main wiki page at https://github.com/usds/us-forms-system/wiki). I don't think this needs to be an exhaustive history of how this project came to be, but rather should simply and succinctly cover:

- What the original problem was that VA faced (worded carefully to make the problem recognizable to other agencies and entities)
- What the solution (the vets.gov forms and, later, the US Forms System) includes that addresses those problems (both technical and strategic)
- Possibly names of groups or individuals who were involved at various points, so that they can be contacted for questions.

> ... some starting points for thinking about how to create a better/frictionless form experience online (vs pdf)

@jcmeloni-usds, can you provide examples of what this might include? Perhaps PRA guidelines (https://github.com/usds/us-forms-system/wiki/PRA-Implications) and accessibility considerations (#253)?

**Comment by ButtersUSDS** [comment]
FWIW, I had imagined a tidy set of government-specific tips and guidelines. Such a guide *could* include:

-  Tips for what form changes might require a PRA review (since it's natural for the form to change at least slightly when going from PDF/Print to Web format)
-  Tips for ensuring 508 compliance (though 508 compliance is built directly into USFS components, some things aren't – like actual content – and some are probably easily overridden – such as color contrast)
- Tips around common patterns when going from a government PDF to a web form, e.g. it's good to put the personal information section at the end vs. beginning so user gets to potential obstacles before spending too much time

To my knowledge, this content does not currently exist as a package, though bits and pieces do. I understand that this might not be the time or place to write such a guide, but it would be nice for the content to be available somewhere in a less piecemeal way, and written for the government audience.

**Comment by bernars-usa** [comment]
> To my knowledge, this content does not currently exist as a package, though bits and pieces do. I understand that this might not be the time or place to write such a guide, but it would be nice for the content to be available somewhere in a less piecemeal way, and written for the government audience.

I agree with @ButtersUSDS that this content would be really useful to a lot of people. What I mentioned to her offline is that if we write this, we're on the hook to ensure it's up-to-date. Furthermore, I don't think the best place for this highly useful information is a wiki on an open source project, hence Ellen's comment that now is not the time or place to write that guide.

**Comment by jcmeloni-usds** [comment]
Closing as won't-fix, but there's good discussion here.
