### ISSUE TITLE
Question from City of Austin Design & Delivery Team...

### ISSUE THREAD

**Issue by mateoclarke** [usds/us-forms-system#54]
Thanks for y'alls leadership in evaluating and recommending react-jsonschema-form as tool for devs in government. I have a question about the underlying mozilla-services library more than this fork of the library but I hope it's still relevant.

As I was doing the evaluation and creating some sample forms, I noticed that react-jsonschema-form doesn't have built in support for events triggered by `onBlur`. Instead they rely on the live validation or `onSubmit`. Here's an issue regarding this limitation including a suggested work-around. 
https://github.com/mozilla-services/react-jsonschema-form/issues/617

Have y'all encountered this obstacle? Have you been able to overcome it with custom code or have you adapted your UX design to validate based on the constraints of the tool out-of-the-box?

If you could point me towards any open-source code of implemented forms, it would be much appreciated.

many thanks!
Mateo Clarke
IT Applications Developer Sr.
City of Austin

cc/ @amenity @cthibaultatx @benweatherman @ifsimicoded

**Comment by kaschm-usds** [comment]
Hello @mateoclarke ! 

Thanks so much for the question, and apologies for the delayed response. We're currently heads down on getting the initial code up and out, but as soon as we're done with that we will jump back on this thread and answer your questions. 

Thanks for your patience!

**Comment by annekainicUSDS** [comment]
Hi @mateoclarke! We have added some custom code to our library in order to handle live validations. We want to run live validations, but we obviously don't want those validations to run until someone has attempted to enter something into the field (if the page loaded with all the fields marked with errors, that would be disconcerting!). We make use of react-jsonschema-form's `onBlur` functionality to set a value for that field indicating that it's been "touched" so that we know we can run our validations on it. Here's an example of what that looks like: https://github.com/usds/us-forms-system/blob/master/src/js/components/SchemaForm.jsx#L89. `SchemaForm` is a us-forms-system wrapper component on top of the react-jsonschema-form library, and will pass that prop down through the field-level components.

I hope this answers your question, but please let me know if you still have further questions!

**Comment by mateoclarke** [comment]
Thanks @annekainicUSDS & @kaschm-usds. This is super neat, appreciate your explanation and linking to the relevant code. I'm glad us-forms-system includes this logic. Looking forward to following your progress.

**Comment by annekainicUSDS** [comment]
No problem! Let us know if we can answer any other questions!
