### ISSUE TITLE
Do Comparative Analysis of Open Source DX

### ISSUE THREAD

**Issue by ButtersUSDS** [usds/us-forms-system#58]
Per [Research Strategy](https://github.com/usds/us-forms-system/wiki/Research-&-Testing-Strategy):

- [x] Choose 4-5 comparable open source developer libraries to compare (include both government and private sector)

- [x] Define criteria & heuristics used for evaluation, then define focal areas for evaluation

- [ ] Do the evaluation, and make sure to also capture recurring patterns in open source library experiences

- [ ] Some of the questions we're hoping to answer: What is the right amount or segmentation of documentation? What is the maximum amount before it becomes too heavy/unusable? How do tools suggest citations or other ways of raising visibility & awareness? What kind of content is often presented in a website wrapper?  

- [ ] Document findings in the Wiki

- [ ] Formally present findings to the team

**Comment by jcmeloni-usds** [comment]
Hi! What's the progress on this?

**Comment by ButtersUSDS** [comment]
@jcmeloni-usds I did the initial part of this, then deprioritized per @amiklik, especially since a major part of the evaulation would need to be done by an engineer. You can see the progress I made in the Comparative Analysis section [here](https://github.com/usds/us-forms-system/wiki/Open-Source-Tools-Comparative-Analysis).

**Comment by amenity** [comment]
Hey y'all! 

In case it's useful, [here's the all-things-forms-spreadsheet](https://docs.google.com/spreadsheets/d/1ov27dpfaFW9nk0mVIpshj5Sj5mxoKaQafk8W4oyvqws/edit#gid=222732060) I mentioned to @kaschm-usds and @jcmeloni-usds at Summit. 

It has a good chunk of comparative analysis, both of of "self-serve" platforms staff can use without the help of a developer (e.g. Seamless Docs) and libraries/dev-tools (e.g. Form.io, Knack). The final sheet links to resources about implementation and ux best practices for digital forms.  

It's been a messy dumping ground since we too had to de-prioritize it. That said, I've spoken to lots of people in other orgs who have said it would be a great resource for them, especially if it includes good 
- Pricing information - a pain to extract from vendors without inviting them to hound you for life
- Thorough accessibility assessments - mobile device performance, etc. that are especially important factors for government delivery of digital services to residents
- Assessment of usability for both engineers and non-technical government staff 

If you think it would be a handy resource for your team, let me know. I'm about to jump back onto evaluating some of these vendor platforms for the City, and I can try to squeeze in a little clean up of this guy along the way. Also, of course, feel free to add/update and share it widely.

**Comment by kaschm-usds** [comment]
@amenity thanks for sharing!

**Comment by kaschm-usds** [comment]
Oh, you like my GDocs-capabilities **now**, don't you @jcmeloni-usds? ;) 

For some reason it won't let me upload to the comment, but it should be [accessible here](https://github.com/kaschm-usds/resources/blob/master/Digital%20Form%20Resources.xlsx)

**Comment by amenity** [comment]
Ah - I was afraid that it might not be IT-approved some places. 

Hope some of it is helpful. Again, it could use some love and is definitely a living document. If you'd like to add anything to it, or get a newer version at some point (we're just beginning to share it actively with other gov teams) let me know.

**Comment by jcmeloni-usds** [comment]
@ju-liem We've drifted in the work here, and I think we know where we are -- can you please double-check all the documentation is correct in the wiki about what we investigated and the conclusions we came to, and then close this issue?  Thanks!
