### ISSUE TITLE
Review & address dependency scanning results

### ISSUE THREAD

**Issue by jcmeloni-usds** [usds/us-forms-system#60]
GitHub's handy dandy scanning tools produced a pretty good report of dependencies w/ vulnerability flags.  I know the code is not fully decoupled, but sooner rather than later let's take a gander at:

https://github.com/usds/us-forms-system/network/dependencies

**Comment by annekainicUSDS** [comment]
I fixed all of the security warnings except for the remaining ones related to node-sass. The difficulty in fixing these is that the latest version of node-sass is using outdated dependencies, whose sub-sub dependencies are the ones triggering the security warning. I don't think I can directly fix this problem because it's related to node-sass's dependencies. When I try to manually install the latest version of the sub-sub dependencies with warnings, due to the dependency graph there is still a problem because node-sass is still specifying the outdated version.

The maintainers of node-sass know that this is an issue: https://github.com/sass/node-sass/issues/2355. It sounds like it will be fixed in their latest release, which should be coming out shortly. I'm tempted to wait for the latest release, which will fix this problem. Are there any other ideas on how to fix this issue? @jordangov or @nacingov?

**Comment by jordangov** [comment]
Not that I can immediately think of... besides switching to the Ruby sass gem.

**Comment by jcmeloni-usds** [comment]
@annekainicUSDS I'm cool w/ waiting

**Comment by jcmeloni-usds** [comment]
@annekainicUSDS do we want a new ticket just to track that one issue?  don't want to lose track of this.

cc @ju-liem @fatimanoorva

**Comment by annekainicUSDS** [comment]
Sure, let's create a new ticket just for the node-sass dependency issues

**Comment by jcmeloni-usds** [comment]
@annekainicUSDS great.  I'll leave that o @ju-liem  or @fatimanoorva to take care of and then close this.

**Comment by ju-liem** [comment]
Per engineering conversation, I'm closing this, and @annekainicUSDS will watch for any node-sass updates to resolve the deeper dependency.
