### ISSUE TITLE
Should USWDS import from VA's design system?

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system#65]
A lot of the styles we use for forms on Vets.gov come from our [design system repo](https://github.com/department-of-veterans-affairs/design-system). How should we include those styles in this project? Right now I'm importing them into our css, but not sure if that's the best approach long-term. Perhaps it should be the reverse (the VA's design system imports from here).

**Comment by jcmeloni-usds** [comment]
My thoughts on this -- as it relates to the USFS primarily, USWDS secondarily, and Vets.gov tertiarily...

* We want users of the USFS to have at their disposal the most responsive, compliant, *vanilla* set of styles possible, so as to a) be useful but b) not be prescriptive.  To me, that means USFS imports USWDS as-is, and that's it, but I understand that doesn't address anything created specifically for USFS, like, uh, forms stuff.
* If there are additions to styles that are specific to USFS -- which I assume there are, see note above -- then those should be wholly present in and only in the USFS code and not dependent (via manual updates or otherwise) from anywhere else (such as jean-pants).
* If USWDS -> USFS styles are then overridden by reference or updates to code in the local repo, e.g. the one for Vets.gov, DHS, USDA, whatever, that's fine.  Let it happen, as long as we have nice documentation about what that means (e.g. we can't say that whatever someone else does is still 508 compliant, etc)
* However, if it's the design system of jean-pants that fundamentally makes the USFS as awesome as it is, then that's definitely a different conversation to have -- I don't currently think that's the case, though?

In my ideal world, USFS imports USWDS, USFS has styles specific to itself that are in the code but not imported from or dependent upon something elsewhere.  So, if a person is using USFS they can get all the benefits from USWDS updates via "uswds: ^1.6.3" in package.json but jean-pants or its ilk should not be imported.  Does that make sense?

**Comment by annekainicUSDS** [comment]
Yes, that makes sense. In starting an app from scratch and importing us-forms-system, I've realized that there are actually a lot of styles that come from the VA design system. I agree that long-term USFS should not be importing from VA design system, but I'm not sure where those styles that are shared between both should live eventually. I'm not sure that duplicating them (having them live in both USFS and VA design system) is the best solution, so it might be best to figure out which styles are truly forms-related and if those be pulled out of the VA design system and into USFS. Teasing out the styles is going to be a huge effort, though, so it's definitely a bigger project we need to plan for.

**Comment by annekainicUSDS** [comment]
A few preliminary questions to answer:

1. Are the files we're importing from VA design system used elsewhere in vets-website besides for code that comes from the forms system?
2. Would it make sense to set up a basic variables files that would enable someone to easily configure styles they would be likely to want to change? Things like colors, fonts, font sizes, etc.?

**Comment by annekainicUSDS** [comment]
Steps to completing this work:
- Move styles from the VA design system into us-forms-system that are only used by us-forms-system code (https://github.com/usds/us-forms-system/pull/91)
- Figure out solution for styles that are shared between VA design system and us-forms-system
- Create basic variables file that would more easily enable users of the library to customize basic things they need

**Comment by annekainicUSDS** [comment]
End goal: USFS should not import any files from VA design system. Steps to accomplish this:
1. Move things from VA design system that are forms related and should really be in this repo
  - Form process styles
  - Progress bar component and styles
2. Remove VA design system files from vets-website that were transferred to USFS
3. Import new USFS into vets-website

**Comment by annekainicUSDS** [comment]
I think separate tickets are a good idea. I can create those.
