### ISSUE TITLE
Publish as npm package

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system#68]

**Comment by jcmeloni-usds** [comment]
Exciting!

**Comment by annekainicUSDS** [comment]
Does USDS have an npm organization? We probably want to publish it under that as opposed to a personal name.

**Comment by jcmeloni-usds** [comment]
@nacingov thoughts?

**Comment by dmethvin-gov** [comment]
It looks like the usds organization name is available, I can create it. They have the option of a free account with unlimited public repos or a $7/month account that allows private repos. I don't think we need private repos do we? We'll only use npm for our public open source projects?

**Comment by jcmeloni-usds** [comment]
@dmethvin-gov We don't need a private repo -- anything we do organizationally will/should be open.  Go for it, unless @nacingov or @dnesting-usa call a halt to doing so (if they don't respond by Friday, just do it and I'll take any heat).

**Comment by dnesting-usa** [comment]
This seems fine to me but @nacingov might have thoughts.

**Comment by dmethvin-gov** [comment]
I'm a person of action so I created https://npmjs.com/org/usds with just free accounts for now. I suspect we could change it if we really want a paid account. A couple of questions:

**Management of the org:** At the moment there are no other npm accounts associated, I need to add some so it's not just me who can manage it. Publish rights for a specific project can be managed separately from the USDS org so perhaps @dnesting-usa and @nacingov for starters? There is [support for two-factor auth on npm](https://docs.npmjs.com/getting-started/using-two-factor-authentication) so I recommend that we all use it.

**Naming of projects:** We can either publish `us-forms-system` at the top public level or inside our org namspace as `@usds/us-forms-system`. If we're intending this to be for public consumption I'd recommend that we put at the top public level. Projects like `us-forms-system-starter-app` don't need to be published on npm since they're not meant to be put in another project's `package.json`. We *could* put them there but I'm not sure it facilitates anything.

**Comment by dnesting-usa** [comment]
> I'm a person of action so I created

I don't care what Nacin says.  You are of our tribe.

**Comment by jcmeloni-usds** [comment]
same

**Comment by dmethvin-gov** [comment]
See #101

**Comment by nacingov** [comment]
For the record, I agree with everything here.

**Comment by dmethvin-gov** [comment]
Here's the way I see it working, ideally:

* Team agrees that we're ready to cut a release
* Someone submits a pull request that includes a new tag with the version number, e.g. `v1.2.3`, pointed to the HEAD of master
  - On the command line you do that via `npm version {patch|minor|major}` followed by `git push && git push --tags`; not sure how the git GUIs do it
* Someone else approves the PR and lands it, starting the CircleCI process
* The CircleCI script "sees" the tag and does an `npm publish`

The remaining questions I have about CircleCI  regard strange scenarios like someone maliciously submitting a PR from their own master that is tagged, we don't want *that* to publish. The CircleCI docs are horribly ambiguous so I've been trying to test it with my own repo to see how it behaves.

If this becomes too much of a hassle we can drop back to one of us manually installing from the command line using `npm publish`.

**What version do you want to start at?** The current version in the package.json is 1.0.0. If we follow semver from the start we're likely to have a bunch of breaking changes as we separate the generic form handling from the vets.gov implementation so it might be better to start with 0.1.0 or something like that.

**Comment by dmethvin-gov** [comment]
USWDS is doing their CircleCI [this way](https://github.com/uswds/uswds/blob/c98f69c879d0fc9e2e2cc72ee9ee9743c1971d39/.circleci/config.yml) which seems better. If someone tries to submit a PR from their fork of the master branch, publishing will fail because we have CircleCI set up to not set environment variables (such as the npm token). It's kind of hacky and means that it's super important that we never enable secrets in the CircleCI control panel, but that is best practice anyway. I've closed my earlier PR and will submit a new one after doing some local testing.

As a team, we still need to decide on a version starting point.

**Comment by dmethvin-gov** [comment]
@annekainicUSDS In general I like the way USWDS is doing their release process and they documented it well so I [based our documentation on theirs](https://github.com/usds/us-forms-system/wiki/Release-process). This makes use of GitHub Releases so it's a nice way to handle release notes etc.

One thing that we might want to change is the branches they use for development versus releases. I talked with @bernars-usa about this and it seems like we have some flexibility on how we want to do the process. 

USWDS uses `master` as their latest *released* version and they do all their *development* work in `develop`. So master at any point in time will not reflect whatever work has already been landed for the next release. It also means that we must branch, rebase and land any PRs against develop, not master. 

What I've used in the past is pretty much the reverse, where the HEAD of `master` includes the latest and greatest that has been landed for the next version but not yet released and there is a separate `releases` branch (or separate releases repo) that holds releases but not any ongoing development work.

There are pros and cons to both approaches no doubt. The times when it becomes most useful is when you have a lot of build artifacts (jsx-->js, scss-->css, map files) that you don't want to put into the repo on every commit but you want to be sure they're included on every release. 

@annekainicUSDS @nacingov do you have any preferences or thoughts on pros/cons here? One thing I've noticed already is that even a one line change to a jsx or scss file generates a lot of noisy changes in the PR since we're committing all the artifacts on every build. Over time that will make the repo pretty heavy and it's often a pain to land prs when they contain artifacts.

**Comment by annekainicUSDS** [comment]
@dmethvin-gov On Vets.gov we did a similar approach to what you describe where `master` is what we develop against and releases go into a branch called `production`, which we don't develop against. I have a slight preference for doing it this way only because `master` is typically what is developed against in most projects I've seen, so might as well keep it consistent with the norm.

I think the question of the artifacts that get created is unrelated to the branches/release question. I agree PRs are noisy, and I'm not sure the way we're currently managed the transpiled/compiled files is the right way anyway. I'd be open to do more investigation into this and to look at how other projects manage these kinds of things.

**Comment by dmethvin-gov** [comment]
If anyone else has thoughts please speak up. Otherwise Anne's suggestion of `master` and `production` sound good to me. I'll do a PR to implement that in addition to updating the draft release notes in the wiki.

**Comment by jcmeloni-usds** [comment]
I'm good with this.  I was going to say that my experience is much like Dave's, which is generally like what Anne said, so go team.

**Comment by dmethvin-gov** [comment]
Fixed by #124 and first version published in #142, see also https://circleci.com/gh/usds/us-forms-system/84 which was the publishing job.
