### ISSUE TITLE
Address unit test messages

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system#84]
There's currently one "Pending" unit test:
`should fill in other formData when a suggestion is selected`

Also this message:
`Warning: Failed prop type: The prop onValueChange is marked as required in ErrorableCheckbox, but its value is undefined.`

**Comment by dmethvin-gov** [comment]
The pending test is this one:
```js
  it.skip('should fill in other formData when a suggestion is selected', () => {});
```
Mocha marks skipped tests as pending. Does this test need to be fleshed out in the next two weeks? If you have an idea of what needs to be done I can try to do it. Otherwise I'd suggest removing it so people aren't concerned about it.

Also, these tests have been copied into the starter project, but `npm test` doesn't work there. If they should work I can create a ticket in that repo.

**Comment by annekainicUSDS** [comment]
@dmethvin-gov I think the test can be removed for now. Not sure why it was added in the first place.

In terms of the tests being in the starter project, do you mean they were copied over in the node module for us-forms-system? I don't think it's necessary to have the tests running in the starter app; the tests are making sure the code from us-forms-system works, and that shouldn't be altered in the starter app. But let me know if you have a different opinion!

**Comment by dmethvin-gov** [comment]
OK, I'll add that change to #89 since it's the other half of what was mentioned here.

Duh I know what happened, my search caught the unit tests in my local us-forms-system-starter-app from node_modules/us-forms-system! Nevermind on that point.

**Comment by annekainicUSDS** [comment]
Sounds good, thanks!
